### PR TITLE
Alerts add

### PR DESCRIPTION
**Pull request by jarvisc1**
Have updated Beni, Mamabase, Biakato, and Mangine. Ready to merge onto master branch. Have already place in the Pcloud

### CODE REVIEW

**Comment by jarvisc1** [comment]
Okay so Aminata has been going over the code and updating French. These reports are consistent with what's in the p cloud now.

**Comment by jarvisc1** [comment]
I'm still seeing some difference so not ready for review yet.

**Comment by thibautjombart** [comment]
Is this ready for review now?

**Comment by eeg31** [comment]
I've uploaded Aminata's code to a new branch/pull request--she say's it's ready for review

**Pull request merged**
